name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - weber8thomas
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Mosaicatcher-pipeline Version
      description: What version of mosaicatcher-pipeline are you running?
      options:
        - 1.5.1 (Default)
        - 1.4.1
        - 1.4
        - 1.3
        - 1.2
        - 1.1
        - 1.0
    validations:
      required: true
  - type: dropdown
    id: mode_of_execution
    attributes:
      label: How did you run the pipeline?
      options:
        - Conda only
        - Conda + Singularity
      validations:
        required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
