# Cluster command
cluster: mkdir -p logs/{rule} errors/{rule} &&
  sbatch
  --partition={resources.partition}
  --qos={resources.qos}
  --cpus-per-task={threads}
  --mem={resources.mem_mb}
  --job-name=smk-{rule}-{wildcards}
  --output=logs/{rule}/%j.out
  --error=errors/{rule}/%j.error
  --time={resources.time}

# Default ressources for all rules
default-resources:
  - partition=htc
  - qos=normal
  - mem_mb=1000
  - time=30

max-jobs-per-second: 500
max-status-checks-per-second: 500
local-cores: 1
latency-wait: 60
jobs: 500

# 7 attempts to restart to correspond to the progressive memory increase solving OOM
restart-times: 7
keep-going: True
rerun-incomplete: True
# scheduler: greedy
