mode: "count"
plot: False
check_sm_tag_in_bam_header: "False"

# Input BAM location
input_bam_ena: "/g/korbel2/weber/MosaiCatcher_files/bam_KG_full/"
# input_bam_location: "/g/korbel2/weber/MosaiCatcher_files/bam_KG_full/"
# input_bam_location: "/g/korbel2/weber/MosaiCatcher_files/PRJEB30027/bam/"
# input_bam_location: "/g/korbel2/weber/MosaiCatcher_files/LCL_TALL/"
input_bam_location: "/g/korbel2/weber/MosaiCatcher_files/bam_KG_full/"

# output_location: "/g/korbel2/weber/MosaiCatcher_output/MosaiCatcher_output_ENA_example_full_test_count2/"
# output_location: "/g/korbel2/weber/MosaiCatcher_output/Mosaicatcher_output_singularity_LCL-TALL/"
output_location: "/g/korbel2/weber/MosaiCatcher_output/Mosaicatcher_output_singularity_bam_KG_full/"
# output_location: "/g/korbel2/weber/MosaiCatcher_output/MosaiCatcher_output_sample_KG_chr21/"
snv_sites_to_genotype: "/g/korbel2/weber/MosaiCatcher_files/snv_sites_to_genotype/ALL.chr1-22plusX_GRCh38_sites.20170504.renamedCHR.vcf.gz"
# FIXME : TMP debuging
# snv_sites_to_genotype: "/g/korbel2/weber/MosaiCatcher_files/snv_sites_to_genotype/split_by_chr/1000G_chr21.vcf.gz"

reference: "/g/korbel2/weber/MosaiCatcher_files/refgenomes_human_local/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
# reference: "/g/korbel2/weber/MosaiCatcher_files/refgenomes_human_local/chr21.fna"

# TODO : add a SMK rule to clone & compile mosaic
mosaicatcher: "/g/korbel2/weber/Gits/mosaicatcher/build/mosaic"

# FIXME : TMP solution for strandphaser location
strandphaser: "/home/tweber/.conda/envs/strandseqnation/lib/R/library/StrandPhaseR/R/StrandPhaseR"
Rscript: "/home/tweber/.conda/envs/strandseqnation/bin/Rscript"

# TODO : remove hard coded paths for R scripts coming from MC
plot_script: "/g/korbel2/weber/Gits/mosaicatcher/R/qc.R"
sv_plot_script: "/g/korbel2/weber/Gits/mosaicatcher/R/chrom.R"
norm_script: "/g/korbel2/weber/Gits/mosaicatcher/R/norm.R"

# CHECKME : check implicit natural path through Conda env
samtools: "/g/funcgen/bin/samtools"
# bcftools: "/biolo/ngs/bin/bcftools"

# TODO : path reference
variable_bins:
  "50000": "/g/korbel2/weber/workspace/pipeline/utils/variable_bins.GRCh38.50kb.bed"
  "100000": "/g/korbel2/weber/workspace/pipeline/utils/variable_bins.GRCh38.100kb.bed"

# TODO : find another solution with conda for R_ref
R_reference: "BSgenome.Hsapiens.UCSC.hg38"

# CHECKME : Parameters optimization ?

exclude_list:
  - BM510x3PE20490

# chromosomes:
#   - chrX
#   - chr22
#   - chr19

chromosomes:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX

# Strandphaser
git_commit_strandphaser: "69c9fb4"
git_repo_strandphaser: "https://github.com/daewoooo/StrandPhaseR"

# Parameters

paired_end: True

## WINDOW
window: 100000

## METHODS
methods:
  - "simpleCalls_llr4_poppriorsTRUE_haplotagsTRUE_gtcutoff0_regfactor6_filterFALSE"
  - "simpleCalls_llr4_poppriorsTRUE_haplotagsFALSE_gtcutoff0.05_regfactor6_filterTRUE"

llr: 4
poppriors: TRUE
haplotags:
  - TRUE
  - FALSE
gtcutoff:
  - 0
  - 0.05
regfactor: 6
filter:
  - TRUE
  - FALSE

## BPDENS
### JOINT SEG
min_diff_jointseg: 0.1
### SINGLE SEG
min_diff_singleseg: 0.5
### SCE CUTOFF
additional_sce_cutoff: 20000000
### SCE MIN DISTANCE
sce_min_distance: 500000

segdups: "data/segdups/segDups_hg38_UCSCtrack.bed.gz"
