name: MosaiCatcher assemblies checks

on:
  push:
    branches:
      - dev
      - arbigent_dev
      - scNOVA

jobs:
  # Downloading_example_data:
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - Linting
  #   #   - Formatting
  #   steps:
  #     - uses: actions/checkout@v3.3.0
  #     - name: Downloading_example_data
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .
  #         snakefile: ./workflow/Snakefile
  #         stagein: "mamba install -c conda-forge unzip"
  #         args: "--cores 1 --config dl_bam_example=True -p --verbose --debug"

  Downloading_hg19:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Downloading_hg19
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --conda-frontend mamba  --config reference=hg19 workflow/data/ref_genomes/config/BSgenome_hg19.ok -p --verbose --debug"
  Downloading_hg38:
    runs-on: ubuntu-latest # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Downloading_hg38
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --conda-frontend mamba  --config reference=hg38 workflow/data/ref_genomes/config/BSgenome_hg38.ok -p --verbose --debug"
  Downloading_T2T:
    runs-on: ubuntu-latest # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Downloading_T2T
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1  --use-conda --conda-frontend mamba --latency-wait 60 --config reference=T2T workflow/data/ref_genomes/config/BSgenome_T2T.ok -p --verbose --debug"
