name: MosaiCatcher assemblies checks

on:
  schedule:
    # Run every Sunday at 00:00 UTC on the master branch
    - cron:  '0 0 * * 0'
      branches:
        - master
  push:
    branches:
      - '*'
      - '!master'


jobs:
  # Downloading_example_data:
  #   runs-on: ubuntu-latest
  #   # needs:
  #   #   - Linting
  #   #   - Formatting
  #   steps:
  #     - uses: actions/checkout@v3.3.0
  #     - name: Downloading_example_data
  #       uses: snakemake/snakemake-github-action@v1.24.0
  #       with:
  #         directory: .
  #         snakefile: ./workflow/Snakefile
  #         stagein: "mamba install -c conda-forge unzip"
  #         args: "--cores 1 --config dl_bam_example=True -p --verbose --debug"

  Downloading_hg19:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Downloading hg19
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1 --use-conda --conda-frontend mamba  --config reference=hg19 -p --verbose --debug workflow/data/ref_genomes/config/BSgenome_hg19.ok"
  Downloading_hg38:
    runs-on: ubuntu-latest # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Downloading hg38
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1 --use-conda --conda-frontend mamba  --config reference=hg38 -p --verbose --debug workflow/data/ref_genomes/config/BSgenome_hg38.ok"
  Downloading_T2T:
    runs-on: ubuntu-latest # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Downloading T2T
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1  --use-conda --conda-frontend mamba --latency-wait 60 --config reference=T2T -p --verbose --debug workflow/data/ref_genomes/config/BSgenome_T2T.ok"
  Downloading_mm10:
    runs-on: ubuntu-latest # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Downloading T2T
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: "--cores 1  --use-conda --conda-frontend mamba --latency-wait 60 --config reference=mm10 -p --verbose --debug workflow/data/ref_genomes/config/BSgenome_mm10.ok"
