name: MosaiCatcher basic checks

on:
  schedule:
    # Run every Sunday at 00:00 UTC on the master branch
    - cron: "0 0 * * 0"
      # branches:
      #   - master
  push:
    branches:
      - "*"
      - "!master"

jobs:
  # WORK
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--lint"
  Testing:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible && mamba install -c bioconda snakemake-storage-plugin-http"
          args: "--cores 1 --use-conda --latency-wait 60 --configfile .tests/config/simple_config.yaml --conda-frontend mamba -p --verbose --debug"
      - name: Testing report
        uses: snakemake/snakemake-github-action@v1.24.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --latency-wait 60 --configfile .tests/config/simple_config.yaml  --conda-frontend mamba --report report.zip"
