name: Tests

on:
  push:
    branches:
      - master
      - smk_workflow_catalog
  pull_request:
    branches_ignore: []

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: "--lint"
