name: MosaiCatcher basic checks

on:
  push:
    branches:
      - dev

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestTEST
        run: |
          ls -alh /home/runner/work/mosaicatcher-pipeline/mosaicatcher-pipeline
  # WORK
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--lint"
  Testing:
    runs-on: ubuntu-latest
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v2
      - name: Test ls
        run: |
          echo $pwd
          ls -lha $pwd
          ls -lha $pwd.tests/data_CHR17
      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          stagein: "conda config --set channel_priority flexible"
          args: '--cores 1 --use-conda --configfile .tests/config/simple_config_github.yaml --config $(pwd).tests/data_CHR17 --conda-frontend mamba -p --verbose --debug
      - name: Testing report
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .
          snakefile: ./workflow/Snakefile
          args: "--cores 1 --use-conda --configfile .tests/config/simple_config_github.yaml --conda-frontend mamba --report report.zip"
