name: Workflow checks

on:
  push:
    branches:
      - master
      - smk_workflow_catalog

jobs:
  # WORK
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: .
          snakefile: ./Snakefile
          stagein: 'file=$(grep snv_sites mosaicatcher-update/config/config.yaml| grep -P -o "sandbox.*") && mkdir -p "${file%/*}" && touch "$file" && file=$(grep -P "^reference" mosaicatcher-update/config/config.yaml| grep -P -o "sandbox.*") && mkdir -p "${file%/*}" && touch "$file" && mamba env remove -n snakemake && mamba create -y -n snakemake -c conda-forge -c bioconda unzip snakemake pandas pysam tqdm imagemagick && source activate snakemake && ls -l && pwd'
          args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    # needs:
    #   - Linting
    #   - Formatting
    steps:
      - uses: actions/checkout@v1

      # - name: Downloading data
      #   uses: snakemake/snakemake-github-action@v1.22.0
      #   with:
      #     directory: .
      #     snakefile: ./Snakefile
      #     stagein: "mamba env remove -n snakemake && mamba create -y -n snakemake -c conda-forge -c bioconda unzip snakemake pandas pysam tqdm imagemagick && source activate snakemake "
      #     args: "--cores 1 --config mode=download_data dl_external_files=True"

      - name: Testing data
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: .
          snakefile: ./Snakefile
          stagein: 'mamba env remove -n snakemake && mamba create -y -n snakemake -c conda-forge -c bioconda snakemake pandas pysam tqdm imagemagick samtools bcftools && source activate snakemake && ls -lh && apt-get update && apt-get install --no-install-recommends -y libssl-dev libcurl4-openssl-dev libboost-program-options libboost-program-options-dev libboost-random-dev libboost-system libboost-system-dev libboost-filesystem libboost-filesystem-dev libboost-iostreams libboost-iostreamsdev libboost-date-time libboost-date-time-dev zlib1g-dev libxml2-dev gawk && apt-get autoremove -y && rm -rf /var/lib/apt/lists/* && BUILD_DEPS="cmake git" && apt-get install --no-install-recommends -y $BUILD_DEPS && git clone https://github.com/friendsofstrandseq/mosaicatcher.git && cd mosaicatcher && git checkout develop && mkdir build && cd build && cmake ../src/ && cmake --build . && cd && ln -s mosaic /usr/local/sbin/mosaic && apt-get remove -y $BUILD_DEPS && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*'
          args: '--cores -12 --config chromosomes="[chr21]" mode=mosaiclassifier plot=True input_bam_location=.test/data/ output_location=.test/output/ --use-conda --latency-wait 60'
